name: OpenRouter Config
version: 1.0.0
schema: v1

models:
  - name: DeepSeek V3
    provider: openai
    model: deepseek/deepseek-chat-v3-0324
    apiBase: https://openrouter.ai/api/v1
    apiKey: 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

  - name: Qwen Coder
    provider: openai
    model: qwen/qwen-2.5-coder-32b-instruct
    apiBase: https://openrouter.ai/api/v1
    apiKey: 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